/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConeccionBDD;
import Controlador.ServiciosBDD;
import Modelo.Cliente;
import Modelo.Horario;
import Modelo.Recorrido;
import Modelo.Reservacion;
import Modelo.Venta;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
//etiResultado.setText(cboNumeros.getSelectedItem().toString());
/**
 *
 * @author Daniela
 */
public class cliente extends javax.swing.JFrame {

    /**
     * Creates new form recorrido
     */
    
    
    private List<Recorrido> arre = new ArrayList<Recorrido>();
    private List<Horario> listaHorario;  
    private Cliente cliente;
    private Reservacion reservacion;
    private String usuario;
    private String contrasena;
    
    public cliente(String usuario, String contrasena) {
        this.usuario = usuario;
        this.contrasena = contrasena;
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            recuperarRecorridos();  
            recuperarHorarios();
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoRecorridos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRecorridos = new javax.swing.JList<>();
        btnSeleccionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        reservacionpanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        DatosC = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        recorrido = new javax.swing.JLabel();
        horario = new javax.swing.JLabel();
        monto = new javax.swing.JLabel();
        identificador = new javax.swing.JTextField();
        nombreC = new javax.swing.JTextField();
        numeroTel = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        reservar = new javax.swing.JButton();
        comboRecorridos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboHorarios = new javax.swing.JComboBox<>();
        cantidadPersonas = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdReservacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();

        jScrollPane1.setViewportView(listaRecorridos);

        btnSeleccionar.setText("Seleccionar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout dialogoRecorridosLayout = new javax.swing.GroupLayout(dialogoRecorridos.getContentPane());
        dialogoRecorridos.getContentPane().setLayout(dialogoRecorridosLayout);
        dialogoRecorridosLayout.setHorizontalGroup(
            dialogoRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoRecorridosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(dialogoRecorridosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar)
                .addGap(64, 64, 64)
                .addComponent(btnCancelar)
                .addGap(196, 196, 196))
        );
        dialogoRecorridosLayout.setVerticalGroup(
            dialogoRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoRecorridosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnCancelar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reservacionpanel.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("RESERVACIÓN DE RECORRIDOS");

        DatosC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DatosC.setText("Datos del cliente");

        nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 51, 51));
        nombre.setText("Nombre completo");

        numero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        numero.setForeground(new java.awt.Color(51, 51, 51));
        numero.setText("Número telefónico");

        cantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cantidad.setForeground(new java.awt.Color(51, 51, 51));
        cantidad.setText("Cantidad Personas:");

        recorrido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        recorrido.setForeground(new java.awt.Color(51, 51, 51));
        recorrido.setText("Recorridos");

        horario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        horario.setForeground(new java.awt.Color(51, 51, 51));

        monto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        monto.setForeground(new java.awt.Color(51, 51, 51));
        monto.setText("Monto total");

        identificador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nombreC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        numeroTel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        total.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        total.setEnabled(false);

        cancelar.setText("CANCELAR");
        cancelar.setBorderPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        reservar.setText("RESERVAR");
        reservar.setBorderPainted(false);
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });

        comboRecorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRecorridosActionPerformed(evt);
            }
        });

        jLabel1.setText("Horarios disponibles:");

        cantidadPersonas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadPersonasStateChanged(evt);
            }
        });

        jLabel2.setText("IdCliente:");

        jLabel3.setText("Datos de la reservación");

        jLabel4.setText("idReservacion");

        jLabel5.setText("IdVenta:");

        javax.swing.GroupLayout reservacionpanelLayout = new javax.swing.GroupLayout(reservacionpanel);
        reservacionpanel.setLayout(reservacionpanelLayout);
        reservacionpanelLayout.setHorizontalGroup(
            reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservacionpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
            .addGroup(reservacionpanelLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservacionpanelLayout.createSequentialGroup()
                        .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero)
                            .addComponent(nombre)
                            .addComponent(DatosC)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(identificador, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(462, 462, 462))
                    .addGroup(reservacionpanelLayout.createSequentialGroup()
                        .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(reservacionpanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdVenta)
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addContainerGap(599, Short.MAX_VALUE))))
            .addGroup(reservacionpanelLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reservacionpanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reservacionpanelLayout.createSequentialGroup()
                        .addComponent(cantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reservacionpanelLayout.createSequentialGroup()
                        .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reservacionpanelLayout.createSequentialGroup()
                                .addComponent(recorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(reservacionpanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(reservacionpanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reservacionpanelLayout.setVerticalGroup(
            reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservacionpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo)
                .addGap(80, 80, 80)
                .addComponent(DatosC)
                .addGap(28, 28, 28)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numero)
                    .addComponent(numeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservacionpanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(reservacionpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtIdReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidad)
                    .addComponent(cantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(horario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monto)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(reservacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservar)
                    .addComponent(cancelar))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservacionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reservacionpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed
    public void agregarCliente() throws SQLException{
        try {
            int id = Integer.parseInt(identificador.getText());
            String nombreCompleto = nombreC.getText();
            String numeroTel = this.numeroTel.getText();
            cliente = new Cliente(id,nombreCompleto,numeroTel);
            ServiciosBDD.agregarCliente(ConeccionBDD.obtener(usuario,contrasena), cliente);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    public void agregarReservacion() throws SQLException{
        int idReservacion = Integer.parseInt(txtIdReservacion.getText());
        int cantidadPersonas = Integer.parseInt(this.cantidadPersonas.getValue().toString());
        String fechayhora = "2021-07-12 00:00:00";
        reservacion = new Reservacion(idReservacion,fechayhora,cantidadPersonas);
        try {
            ServiciosBDD.agregarReservacion(ConeccionBDD.obtener(usuario, contrasena), reservacion);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    public void agregarVenta(){
        int idventa = Integer.parseInt(txtIdVenta.getText());
        String fecha = "2021-07-07 09:30:00";
        double monto = Double.parseDouble(total.getText().replace("$", ""));
        int idReservacion = Integer.parseInt(txtIdReservacion.getText());
        Venta nuevaVenta = new Venta(idventa,fecha,monto,idReservacion);
        try {
            ServiciosBDD.agregarVenta(ConeccionBDD.obtener(usuario, contrasena), nuevaVenta);            
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void AgregarClienteReservacion() throws SQLException{
        int indice1 = comboRecorridos.getSelectedIndex();
        int indice2 = comboHorarios.getSelectedIndex();
        if(indice1 != -1||indice2 != -1){
            Horario h = listaHorario.get(indice2);
            Recorrido r = arre.get(indice1);
            try {
                agregarCliente();
                agregarReservacion();
                agregarVenta();
                ServiciosBDD.agregarClienteReservacion(ConeccionBDD.obtener(usuario, contrasena), h, r);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "selecciona un recorrido y un horario");
        }
        
        
        
    }
    public void recuperarHorarios() throws SQLException{
        DefaultComboBoxModel modeloHorarios = new DefaultComboBoxModel();
        try {
            listaHorario = ServiciosBDD.getHorarios(ConeccionBDD.obtener(usuario, contrasena));
            for(Horario horario: listaHorario){
                modeloHorarios.addElement(horario.getFechayhora());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        comboHorarios.setModel(modeloHorarios);
        comboHorarios.setSelectedIndex(0);
    }
    
    public void recuperarRecorridos() throws SQLException{
        DefaultComboBoxModel modeloRecorridos = new DefaultComboBoxModel();
        try {                      
            arre = ServiciosBDD.getRecorridos(ConeccionBDD.obtener(usuario,contrasena));                      
            for(Recorrido recorrido: arre){
               modeloRecorridos.addElement( recorrido.getNombre());               
            }
            comboRecorridos.setModel(modeloRecorridos);
            comboRecorridos.setSelectedIndex(0);
            
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    
    }
    public void calcularTotal(){
        if(arre.size()!= 0){
           int cantPersonas = Integer.parseInt(cantidadPersonas.getValue().toString());
           int indice = comboRecorridos.getSelectedIndex();
           double precio = arre.get(indice).getPrecio_Unitario() * cantPersonas;
           total.setText("$" + precio);
       }
    }
    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
        try {
            AgregarClienteReservacion();
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_reservarActionPerformed

    private void cantidadPersonasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadPersonasStateChanged
       calcularTotal();
    }//GEN-LAST:event_cantidadPersonasStateChanged

    private void comboRecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRecorridosActionPerformed
        calcularTotal();
        try {
            recuperarHorarios();
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_comboRecorridosActionPerformed
    public void inicializarVentana(){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente(usuario,contrasena).setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatosC;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JSpinner cantidadPersonas;
    private javax.swing.JComboBox<String> comboHorarios;
    private javax.swing.JComboBox<String> comboRecorridos;
    private javax.swing.JDialog dialogoRecorridos;
    private javax.swing.JLabel horario;
    private javax.swing.JTextField identificador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaRecorridos;
    private javax.swing.JLabel monto;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreC;
    private javax.swing.JLabel numero;
    private javax.swing.JTextField numeroTel;
    private javax.swing.JLabel recorrido;
    private javax.swing.JPanel reservacionpanel;
    private javax.swing.JButton reservar;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtIdReservacion;
    private javax.swing.JTextField txtIdVenta;
    // End of variables declaration//GEN-END:variables
}
